### ISSUE TITLE
ModuleNotFoundError: No module named 'StringIO'

### ISSUE THREAD

**Issue by bashu** [praekelt/django-export#28]
```python
/Users/bashu/.virtualenvs/musicaviva/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/bashu/.virtualenvs/musicaviva/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/bashu/.virtualenvs/musicaviva/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/bashu/.virtualenvs/musicaviva/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/bashu/.virtualenvs/musicaviva/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/Users/bashu/.virtualenvs/musicaviva/lib/python3.6/site-packages/object_tools/apps.py", line 13, in ready
    self.module.autodiscover()
  File "/Users/bashu/.virtualenvs/musicaviva/lib/python3.6/site-packages/object_tools/__init__.py", line 36, in autodiscover
    autodiscover_modules('tools', register_to=tools)
  File "/Users/bashu/.virtualenvs/musicaviva/lib/python3.6/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/bashu/.virtualenvs/musicaviva/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/bashu/.virtualenvs/musicaviva/src/django-export/export/tools.py", line 13, in <module>
    from export import forms, tasks, utils
  File "/Users/bashu/.virtualenvs/musicaviva/src/django-export/export/tasks.py", line 1, in <module>
    from export.utils import mail_export
  File "/Users/bashu/.virtualenvs/musicaviva/src/django-export/export/utils.py", line 1, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by bashu** [comment]
ignore this
